# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://cdn.cocoapods.org/'
target 'Account' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Account
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'FMDB', '~> 2.7.5'
  pod 'SDWebImage'
  pod 'GPUImage'
end
