# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


source 'https://github.com/volcengine/volcengine-specs.git'
source 'https://cdn.cocoapods.org/'

target 'Account' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Account
#  pod 'VEAppUpdateHelper', :path => '../../VEAppUpdateHelper/VEAppUpdateHelper.podspec', :subspecs=>[
#  'VEUpdateHelper',
#  'VEUpdateView'
#  ]
	
  pod 'VEAppUpdateHelper', :subspecs=>[
  'VEUpdateHelper',
  'VEUpdateView'
  ]
  
  pod 'RangersAppLog', :subspecs => [
        'Core',
        'Host/CN',
        'OneKit',
        'UITracker',
        'Picker',
        'Log',
        'Unique'
      ]
end
